[3기-C 권성준] springboot-url-shortener 과제 제출합니다.
prgrms-be-devcourse/springboot-url-shortener pull request #30
Opened 2023-01-04 14:14 UTC by Seongjun-Kwon

## 📌 과제 설명
공태현(@rhdtn311 ) 님과 페어 프로그래밍을 통해 구현하였습니다.
코드리뷰 잘 부탁드리겠습니다! 😁

## 👩‍💻 요구 사항
- [x] URL 입력폼 제공 및 결과 출력
- [x] URL Shortening Key는 8 Character 이내로 생성
- [x] 단축된 URL 요청시 원래 URL로 리다이렉트
- [x] 단축된 URL에 대한 요청 수 정보저장 (optional)
- [ ] Shortening Key를 생성하는 알고리즘 2개 이상 제공하며 애플리케이션 실행중 동적으로 변경 가능 (optional)
---
## 👩‍💻 구현 내용
### API 문서
#### 1. URL 입력폼 화면 제공
| 메서드 | URL
:---: | :---: |
GET | / 
---
#### 2. 단축된 URL 생성
| 메서드 | URL
:---: | :---:
POST | /shortener

| Response Parameter | 타입 | 설명
:---: | :---: | :---:
originUrl | String | 원래 URL
shortUrl | String | 단축된 URL
requestCount | Number | 요청 수
---
#### 3. 생성된 상세 결과 페이지 제공 (원래 URL, 단축된 URL, 요청 수)
| 메서드 | URL
:---: | :---: 
GET | /shortener

| Request Parameter | 타입 | 설명
:---: | :---: | :---:
originUrl | String | 원래 URL
shortUrl | String | 단축된 URL
requestCount | Number | 요청 수
---
#### 4. 단축된 URL 로 요청 시 원래 URL 로 리다이렉트
| 메서드 | URL
:---: | :---:
GET | /{shortUrl}

| Path Parameter | 타입 | 설명
:---: | :---: | :---:
shortUrl | String | 단축된 URL
---
### DB 테이블
| 컬럼 명 | 타입 | NULL 가능 | 키 | 설명
:---: | :---: | :---: | :---: | :---:
id | bigint | x | pk | ID 값
algorithm | varchar(20) | x | uk| 알고리즘
origin_url | varchar(2000) | x | uk | 원래 URL
short_url | varchar(7) | o | - |단축된 URL
request_count | bigint | x | - | 요청 수
---

2023-01-06 12:01 UTC, ksy90101 commented on src/main/java/com/programmers/springbooturlshortener/domain/algorithm/Base62Algorithm.java
> +        StringBuilder sb = new StringBuilder();
sb보단 더 의미는 단어를 사용하시면 어떨까요?

2023-01-06 12:02 UTC, ksy90101 commented on src/main/java/com/programmers/springbooturlshortener/domain/algorithm/Base62Algorithm.java
> +public class Base62Algorithm {
Algorithm이 변경될수도 있으니, 인터페이스로 확장성을 지켜보면 어떨까요?

2023-01-06 12:02 UTC, ksy90101 commented on src/main/java/com/programmers/springbooturlshortener/domain/algorithm/Base62Algorithm.java
> +                sb.append("A");
'A'는 어떤 의미일까요?
상수화 시켜주면 좋을거 같아요.

2023-01-06 12:02 UTC, ksy90101 commented on src/main/java/com/programmers/springbooturlshortener/domain/url/Url.java
> +                )
👍

2023-01-06 12:03 UTC, ksy90101 commented on src/main/java/com/programmers/springbooturlshortener/domain/url/Url.java
> +    private Long requestCount;
이거 하다가 locking 걸릴수도 있을거 같은데요?

2023-01-06 12:03 UTC, ksy90101 commented on src/main/java/com/programmers/springbooturlshortener/domain/url/dto/UrlServiceRequestDto.java
> +			.requestCount(1L)
dto가 아니라, entity에 default 값으로 지정해두면 어때요?

2023-01-06 12:04 UTC, ksy90101 commented on src/main/java/com/programmers/springbooturlshortener/domain/url/dto/UrlCreateDto.java
> +		}
이겨있는 값들도 상수화 👍

2023-01-06 12:04 UTC, ksy90101 commented on src/main/java/com/programmers/springbooturlshortener/domain/url/dto/UrlCreateDto.java
> +			return this.originUrl.replace("https://", "");
DTO에서 이런걸 하는게 맞을까요?

2023-01-06 12:04 UTC, ksy90101 commented on src/main/java/com/programmers/springbooturlshortener/domain/url/UrlService.java
> +		Optional<Url> optionalUrl = urlRepository.findByOriginUrl(urlRequestDto.originUrl());
OriginalUrl을 어느곳에서도 저장하지 않는데, 어떻게 DB에서 조회하죠?

2023-01-06 12:05 UTC, ksy90101 commented on src/main/java/com/programmers/springbooturlshortener/domain/url/UrlService.java
> +			return new UrlResponseDto(url.getOriginUrl(), url.getShortUrl(), url.getRequestCount());
오오 중복조회 👍

2023-01-06 12:06 UTC, ksy90101 commented on src/main/java/com/programmers/springbooturlshortener/domain/url/UrlService.java
> +		savedUrl.setShortUrl(shortUrl);
한번에 Insert는 못하나요?

2023-01-06 12:06 UTC, ksy90101 commented on src/main/java/com/programmers/springbooturlshortener/domain/url/util/UrlValid.java
> +public @interface UrlValid {
멋지네요 👍

2023-01-06 12:07 UTC, ksy90101 requested changes
잘 구현했네요 👍 
피드백만 확인해주세요~

2023-01-08 12:02 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/springbooturlshortener/domain/algorithm/Base62Algorithm.java
> +                sb.append("A");
패딩에 사용되는 문자이기에 PADDING_TOKEN 이름으로 상수화했습니다.

2023-01-08 12:09 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/springbooturlshortener/domain/algorithm/Base62Algorithm.java
> +        StringBuilder sb = new StringBuilder();
인코딩된 문자를 붙여주는 역할을 하기에 encodedTokenAppender 로 네이밍했습니다.

2023-01-08 12:19 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/springbooturlshortener/domain/url/dto/UrlCreateDto.java
> +		}
"http://" -> HTTP_PROTOCOL

2023-01-08 12:22 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/springbooturlshortener/domain/algorithm/Base62Algorithm.java
> +public class Base62Algorithm {
수정했습니다!

2023-01-08 12:46 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/springbooturlshortener/domain/url/dto/UrlServiceRequestDto.java
> +			.requestCount(1L)
수정했습니다. 
디폴트 값을 정해주는 것을 @Column 의 columnDefinition 속성으로 넣어주어서 DB 레벨에서 넣을지, 아니면 코드 레벨에서 생성자에 넣어줄지가 고민이 되었습니다.
jpa 의 auto ddl 옵션을 쓰지 않는 경우도 있으니 코드 레벨에서 생성자에 디폴트 값을 넣어주는 방식을 이용했습니다.

2023-01-08 15:22 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/springbooturlshortener/domain/url/UrlService.java
> +		savedUrl.setShortUrl(shortUrl);
현재 로직에서 auto increment 로 생성된 id 값을 인코딩해서 short URL 을 만듭니다.
그렇기에 shortURL 을 업데이트 해주는 로직이 필요합니다.
만약 DB 에서 생성된 값을 이용하지 않는다면 한번에 insert 가 가능할 것 같습니다.

2023-01-08 17:58 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/springbooturlshortener/domain/url/dto/UrlCreateDto.java
> +			return this.originUrl.replace("https://", "");
dto 는 데이터 전송만 담당하고 값을 수정하는 책임을 가지는 건 옳지 않은 것 같습니다.
사용자에게 받은 URL 에서 프로토콜 정보를 제거하는 로직은 엔티티가 가지도록 변경했습니다.

추가적으로 인코딩된 AAAAAAB 같은 값에 도메인 정보를 붙여서 사용자가 사용할 수 있는 localhost:8080/AAAAAAB 로 바꾸는 로직은 도메인 정보가 변경될 수 있으므로 프론트 측이 하는 것이 좋다고 생각하여 옮겼습니다!

2023-01-08 20:07 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/springbooturlshortener/domain/url/Url.java
> +    private Long requestCount;
수정했습니다!
service 레이어 하나를 더 만들어서 해결해봤는데 괜찮은 방식인지 궁금합니다!

2023-01-09 09:50 UTC, ksy90101 approved these changes

2023-01-09 09:50 UTC, ksy90101 commented
고생했어요.

2023-01-09 09:50 UTC, merged