[3기-C 김소현, 박세준, 이수영] springboot-url-shortener 과제 제출합니다.
prgrms-be-devcourse/springboot-url-shortener pull request #32
Opened 2023-01-06 08:00 UTC by twotwobread

## 📌 과제 설명 
SprintBoot URL Shortener 구현 미션
  
Marco 팀원들과의 페어 프로그래밍을 통해 구현했습니다.
<페어 프로그래밍 참여팀원>
- [김소현](https://github.com/thguss)
- [박세준](https://github.com/park-se-jun)
- [이수영](https://github.com/twotwobread)

## 👩‍💻 요구 사항과 구현 내용 
- [x] URL 입력폼 제공 및 결과 출력
- [x] URL Shortening Key는 8 Character 이내로 생성
- [x] 단축된 URL 요청시 원래 URL로 리다이렉트
- [ ] 단축된 URL에 대한 요청 수 정보저장 (optional)
- [ ] Shortening Key를 생성하는 알고리즘 2개 이상 제공하며 애플리케이션 실행중 동적으로 변경 가능 (optional) 

## 구현 내용
1. 원본 URL 입력하고 submit 버튼을 클릭합니다.
2. 해당 URL이 유효한 지, 존재하는 지 검증합니다.
3. Unique Key를 8문자로 생성합니다.
4. 해당 Unique Key와 원본 URL을 DB에 저장합니다.
5. localhost:8080/{Unique Key} 로 접근 시 DB를 조회하여 원본 URL로 redirect합니다.

## 초기 환경 설정
1. 먼저 프로젝트 디렉토리 가장 상위에 있는 `docker-config` 라는 디렉토리로 이동하여 인텔리제이를 이용해 `docker-compose.yml` 파일을 실행합니다.
2. 그 후, DataSource 설정을 위해서 인텔리제이에서 `shift`를 두번 연타 후 `DataSource and Drivers`로 들어갑니다.
3. 거기서 DataSource 메뉴에서 왼쪽 상단의 `+` 버튼을 클릭하고 `MySQL`을 선택합니다.
4. 그 후 아래의 그림과 같이 설정합니다.
- Host: localhost, Port: 3306
- User: root
- Password: root1234!
- URL: jdbc:mysql://localhost:3306
5. `docker-config` 디렉토리에 존재하는 `init/init.sql` 파일을 실행합니다.

## ✅ PR 포인트 & 궁금한 점 
1. 현재 URL 검증 로직을 controller에서 처리하게 구현했는데 이 로직을 비즈니스 로직으로 보고 service에 포함되는 것이 맞는지 아니면 현재 구현처럼 controller에서 처리하는 것이 맞는지 궁금합니다.

2023-01-06 11:51 UTC, ksy90101 commented on build.gradle
> +    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-validation
이런 주석은 삭제해주셔도 될거 같아요.

2023-01-06 11:51 UTC, ksy90101 commented on build.gradle
> +    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-validation'
아래처럼 하나로 통일하면 어떄요?

2023-01-06 11:51 UTC, ksy90101 commented on build.gradle
> +    implementation 'io.seruco.encoding:base62:0.1.3'
라이브러리 잘 찾으셨네요 👍

2023-01-06 11:52 UTC, ksy90101 commented on src/main/java/com/example/urlshortenert2/ShorteningKeyMaker/MyShorteningKeyMaker.java
> +        if (sb.length() >= SHORT_URL_LENGTH) {
sb보단 더 의미는 단어를 쓰는게 좋을거 같아요.

2023-01-06 11:52 UTC, ksy90101 commented on src/main/java/com/example/urlshortenert2/ShorteningKeyMaker/MyShorteningKeyMaker.java
> +public class MyShorteningKeyMaker implements ShorteningKeyMaker {
👍 interface

2023-01-06 11:53 UTC, ksy90101 commented on src/main/java/com/example/urlshortenert2/controller/ShortenerApiController.java
> +@CrossOrigin(origins = "*", allowedHeaders = "*")
CORS를 이렇게 다 풀면 보안상 좋지 않을거 같아요.

아울러 Controller가 아니라 Config로 관리해보면 어떨까요?

2023-01-06 11:54 UTC, ksy90101 commented on src/main/java/com/example/urlshortenert2/controller/ShortenerApiController.java
> +
Handler는 따로 분리하는게 좋을거 같아요.

2023-01-06 11:54 UTC, ksy90101 commented on src/main/java/com/example/urlshortenert2/controller/ShortenerApiController.java
> +        urlValidate(dto.url());
validate를 controller에서 하는 이유가 잇나요?

2023-01-06 11:54 UTC, ksy90101 commented on src/main/java/com/example/urlshortenert2/controller/ShortenerApiController.java
> +        return ResponseEntity.ok().body(shortenerUrl);
제네릭으로 body type을 지정해주는게 좋을거 같아요.

2023-01-06 11:54 UTC, ksy90101 commented on src/main/java/com/example/urlshortenert2/controller/ShortenerApiController.java
> +        if (200 > responseCode || responseCode >= 400) {
200, 400에 대해선 상수화 코드를 사용하는게 어떨까요?

2023-01-06 11:55 UTC, ksy90101 commented on src/main/java/com/example/urlshortenert2/dto/ShortenerRequestDto.java
> +public record ShortenerRequestDto(String url) {
👍

2023-01-06 11:55 UTC, ksy90101 commented on src/main/java/com/example/urlshortenert2/model/ShortedUrl.java
> +    }
loombok쓰실꺼면, 여기도 lombok으로 해도 되지 않을까요?

2023-01-06 11:56 UTC, ksy90101 commented on src/main/java/com/example/urlshortenert2/model/ShortedUrl.java
> +    }
setter를 쓸 이유가 있나요?

2023-01-06 11:56 UTC, ksy90101 commented on src/main/java/com/example/urlshortenert2/model/ShortedUrl.java
> +    public ShortedUrl(String shorteningKey, String originUrl) {
생성자는 메서드 보다 위에 있어야 할거 같아요.

2023-01-06 11:56 UTC, ksy90101 commented on src/main/java/com/example/urlshortenert2/repository/ShortedUrlRepository.java
> +    Optional<ShortedUrl> findShortedUrlByShorteningKey(String shorteningKey);
이렇게 했을때, 조회 속도 생각해봤나요?
String을 조건을 거는거라서요.

2023-01-06 11:57 UTC, ksy90101 commented on src/main/java/com/example/urlshortenert2/service/ShortenerService.java
> +        shortedUrl.setShorteningKey(shorteningKey);
ShortedUrl이 생성되지 않았는데, 미리 저장하는 이유가 무엇인가요?
그냥 Instert하나만 하면 되지 않나요?

2023-01-06 11:59 UTC, ksy90101 commented on src/main/java/com/example/urlshortenert2/model/ShortedUrl.java
> +    @Column(unique = true)
Unique하지 않은 값이 들어올 경우는 없나요?

2023-01-06 11:59 UTC, ksy90101 requested changes
세분이서 너무 잘 구현해주셨네요 👍 
간단한 피드백 남겼으니 확인해보세요~

2023-01-06 12:06 UTC, ksy90101 commented on src/main/java/com/example/urlshortenert2/service/ShortenerService.java
> +    public ShortenerResponseDto createShortener(ShortenerRequestDto dto) {
이미 파싱된 주소는 원래있는걸로 내려주면, 데이터가 많이 안쌓이지 않을까요?

2023-01-09 11:31 UTC, thguss commented on src/main/java/com/example/urlshortenert2/controller/ShortenerApiController.java
> +        urlValidate(dto.url());
@ksy90101 controller 단에서 validate 하여 가능한 빠르게 예외를 던져 처리하고, 검증된 데이터를 비즈니스 로직으로 넘겨주는 것이 흐름 상 적합하다고 생각해서 위와 같이 처리했습니다!

2023-01-09 11:34 UTC, park-se-jun commented on src/main/java/com/example/urlshortenert2/controller/ShortenerApiController.java
> +        return ResponseEntity.ok().body(shortenerUrl);
잘 이해가 되지 않습니다....😵 좀더 구체적으로 설명해 주시면 반영하겠습니다....

2023-01-09 12:20 UTC, thguss commented on src/main/java/com/example/urlshortenert2/repository/ShortedUrlRepository.java
> +    Optional<ShortedUrl> findShortedUrlByShorteningKey(String shorteningKey);
unique key인 shortenKey를 조건으로 조회하는 쿼리라서 속도 면에서 큰 무리가 없을 것이라고 생각했습니다. 
혹시 unique key여도 String을 조건으로 걸면 조회 성능이 좋지 않은 걸까요??

2023-01-09 12:22 UTC, park-se-jun commented on src/main/java/com/example/urlshortenert2/model/ShortedUrl.java
> +    }
JPA의 Entity에 Lombok의 @EqualsAndHashCode를 사용하게 될 경우 실제 내부의 구현사항을 저희가 알 수 없습니다. 하지만 JPA의 Entity에서 equals 와 hashcode 를 다루게 되면 양방향 연관관계를 가지는 entity의 경우 stackOverflowError 예외가 발생할 수 있기 때문에, @EqualsAndHashCode를 사용하지 않고, 직접 equals 와 hashcode 를 override 하였습니다.

ps. 직접만들었음에도 순환참조를 할 수 있는 상태로 구현했다는걸 깨닫고 id 만으로 비교하도록 변경하였습니다.

2023-01-09 12:22 UTC, park-se-jun commented on src/main/java/com/example/urlshortenert2/model/ShortedUrl.java
> +    }
저희는 shoreningKey를 id를 기준으로 만드는 로직입니다. id에  auto generated를 걸어뒀기 때문에, Entity의 생성시점에서 ShorteningKey를 만들지 못하고, 추후 service 레이어에서 setter로 세팅해 주기 때문에 setter를 사용하였습니다. 더 좋은 방법이 있다면 알려주시면 감사하겠습니다!!

2023-01-09 12:22 UTC, thguss commented on src/main/java/com/example/urlshortenert2/service/ShortenerService.java
> +        shortedUrl.setShorteningKey(shorteningKey);
@ksy90101 save를 먼저 하여 id 값을 반환하기 위해서 입니다. 저희는 id 값을 인코딩하여 shorteningKey로 생성했기 때문에 save 로직 후 따로 shorteningKey를 업데이트 해주는 로직으로 구현했습니다.

2023-01-09 12:22 UTC, park-se-jun commented on src/main/java/com/example/urlshortenert2/controller/ShortenerApiController.java
> +        if (200 > responseCode || responseCode >= 400) {
변경했습니다.

2023-01-09 12:24 UTC, thguss commented on src/main/java/com/example/urlshortenert2/model/ShortedUrl.java
> +    @Column(unique = true)
@ksy90101 내부적으로 생성된 unique한 id 값을 인코딩하여 생성하는 데이터라서 unique 한 값이라고 판단하여 구현하였습니다.

2023-01-09 12:45 UTC, thguss commented on src/main/java/com/example/urlshortenert2/service/ShortenerService.java
> +    public ShortenerResponseDto createShortener(ShortenerRequestDto dto) {
@ksy90101 이미 파싱된 주소가 존재하면, 존재하는 origin url을 내려주는 로직을 추가했습니다!

다만, 저희가 코드리뷰를 반영하면서 논의하다가 같은 origin url 이라도 특정 shorted url에 대해서 유입된 사용자의 수 등을 분석하기 위한 데이터가 필요하다면 기존의 같은 origin url을 쌓는 로직도 데이터 수집 측면에서 필요하다고 보는데 어떻게 생각하시나요?

2023-06-05 18:45 UTC, closed without merging